FROM openjdk:8-jre-alpine
# Set the working directory to /app
WORKDIR /app
# Copy the current directory contents into the container at /app
ADD . /app
RUN apk add --no-cache --upgrade bash
CMD ["sh", "test_batch.sh"]